groups:
- name: http_errors
  rules:
  - alert: HighErrorRate
    expr: sum(increase(http_server_requests_seconds_count{status=~"5.."}[30s])) > 10
    for: 0m
    labels:
      severity: critical
      team: backend
    annotations:
      summary: "High number of HTTP 5xx errors"
      description: "There have been more than 10 HTTP 5xx errors in the last 30 seconds"
      dashboard_url: "https://grafana.example.com/d/http-metrics-01"
      runbook_url: "https://wiki.example.com/runbooks/high_error_rate"